sudo: required
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encryp
ted_9f3b5599b056_iv -in service-account.json.enc -out service-acco
unt.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project multi-k8s-347513
  - gcloud config set compute/zone asia-southeast1-a
  - gcloud container cluster get-credentials multi-cluster



